// Equity curve data — language-independent, 2021-05 to 2026-04 (61 points, base=100)
// CL=F: computed from monthly_returns in multi_asset_hmm_bb_rsi_v1_cl_report.json
// SPY/QQQ: monthly close prices normalized, index-0 = 2021-05-01 (prepended 100.0)
window.EQUITY_CURVE = {
  cl:  [100.0,100.0,100.0,108.88,116.75,116.75,116.75,105.12,114.91,114.91,114.91,114.91,114.91,114.91,114.91,114.91,114.91,119.01,125.15,123.43,119.91,119.91,119.91,124.9,124.9,126.95,135.63,135.63,135.63,135.63,142.08,142.84,144.91,144.91,144.91,144.91,144.91,146.29,153.07,154.88,159.08,162.56,162.56,162.56,162.56,162.56,164.43,160.81,160.81,174.21,174.21,174.21,174.21,179.1,182.79,184.24,191.4,191.4,191.4,191.4,191.4],
  spy: [100.0,100.0,102.24,104.74,107.86,102.83,110.04,109.16,114.21,108.18,104.99,108.94,99.38,99.6,91.39,99.8,95.73,86.88,93.94,99.17,93.45,99.33,96.83,100.42,102.02,102.5,109.14,112.71,110.88,105.62,103.33,112.76,117.91,119.79,126.04,130.16,124.91,131.23,135.86,137.51,140.72,143.68,142.39,150.89,147.26,151.21,149.29,140.97,139.75,148.53,156.17,159.76,163.04,168.85,172.87,173.21,173.35,175.9,174.38,165.77,181.01],
  qqq: [100.0,100.0,106.26,109.3,113.91,107.44,115.89,118.2,119.56,109.11,104.22,109.09,94.26,92.76,84.5,95.1,90.22,80.72,83.95,88.6,80.61,89.19,88.87,97.31,97.8,105.51,112.17,116.5,114.77,108.94,106.69,118.23,124.84,127.11,133.82,135.53,129.6,137.57,146.47,144.02,145.61,149.42,148.13,156.06,156.77,160.16,155.83,144.01,146.02,159.42,169.6,173.71,175.37,184.8,193.63,190.61,189.33,191.66,187.17,177.89,199.98],
  // x-axis: indices into the 61-point arrays where each year label is positioned
  // index 0 = 2021-05-01, index 9 = Jan 2022, index 21 = Jan 2023, index 33 = Jan 2024, index 45 = Jan 2025
  yearLabels: ['2021','2022','2023','2024','2025'],
  yearIndices: [0, 9, 21, 33, 45],
};

// Bilingual copy — window.COPY
window.COPY = {
  ja: {
    nav: { products: 'プロダクト', pricing: '料金', install: 'インストール', docs: 'ドキュメント', roadmap: 'ロードマップ', faq: 'FAQ', follow: 'フォロー' },
    hero: {
      tag: '開発進行中',
      h1a: 'ノイズから、',
      h1b: 'シグナルへ。',
      desc: 'バックテスト・ベイズ最適化・ウォークフォワード検証をひとつの CLI で完結。先物・株式・FX を問わず、統計的に再現可能な投資戦略を体系的に開発・証明する。',
      cta1: '無料で試す',
      cta2: 'プランを見る',
    },
    freeStart: {
      label: 'Free で開始',
      title: '無料で検証を始める',
      subtitle: 'Free プランでは、バックテスト・ウォークフォワード分析・ベイズ最適化をローカル環境で試せます。まずはサンプル戦略を動かし、AlphaForge の検証フローを確認してください。',
      primaryCta: 'インストールへ進む',
      secondaryCta: '料金比較を見る',
      updateCta: '更新情報をXで追う',
      availability: 'Free 登録・販売開始は今夏提供開始予定です。現時点ではインストール手順と提供範囲を確認できます。',
      outExamplesCta: '出力サンプルを見る',
      steps: [
        { num: '01', title: 'インストール', desc: 'macOS / Linux / Windows の手順に沿って CLI を準備します。' },
        { num: '02', title: 'サンプル戦略を実行', desc: '用意された戦略 JSON でバックテストと検証フローを試します。' },
        { num: '03', title: '結果を見る', desc: '指標、損益曲線、制限内の最適化結果を確認します。' },
      ],
      limits: [
        'データは2023年12月31日まで',
        '最適化50回',
        'Pine Script生成なし',
      ],
    },
    heroStats: [
      { val: '3', accent: false, lbl: '開発中プロダクト' },
      { val: 'Sharpe 1.09', accent: true, lbl: 'シミュレーション実績（CL=F・5年データ）' },
      { val: '2026夏', accent: false, lbl: '正式リリース目標' },
    ],
    pricing: {
      label: '料金',
      title: '使い方に合わせて\n選べるプラン',
      subtitle: 'ローンチ記念: 先着 50 名は Lifetime を $299 で販売（通常 $799）。Annual / Monthly は通常価格で提供します。',
      freePlan: {
        title: 'Free プランで始める',
        badge: 'Free',
        desc: 'バックテスト・ベイズ最適化・ウォークフォワード分析を無料で試せます。\n2023年12月31日までのデータ・最適化50回上限・Pine Script 生成なし。',
        pills: [
          { label: '✓ バックテスト',       type: 'ok' },
          { label: '✓ ウォークフォワード', type: 'ok' },
          { label: '最適化 50回上限',      type: 'limit' },
          { label: 'データ 〜2023/12/31',   type: 'limit' },
          { label: 'Pine Script 生成',     type: 'no' },
        ],
        ctaLabel: '$0 で登録',
        ctaHint: 'インストール手順へ',
        comingSummer: '今夏提供開始予定',
      },
      plans: [
        {
          name: 'Lifetime（Early Bird）',
          badge: 'ローンチ記念・先着50名',
          featured: true,
          price: '$299',
          period: '買い切り',
          desc: '販売開始から2週間限定・先着50名様への早割価格。通常 $799 が $299。v1.x 系の全アップデート対象。',
          features: [
            'macOS / Linux / Windows 対応',
            'シミュレーション（回数無制限）',
            'ベイズ最適化（Optuna）',
            'ウォークフォワード分析',
            'Pine Script v6 自動生成',
            'v1.x の全アップデート対象（v2 は50%アップグレード）',
            '個人利用の範囲で複数端末対応',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
        {
          name: 'Annual',
          badge: null,
          featured: false,
          price: '$159',
          period: '/ 年',
          desc: '年間サブスクリプション。Monthly比 約30% お得。常に最新バージョンを利用できます。',
          features: [
            'macOS / Linux / Windows 対応',
            'シミュレーション（回数無制限）',
            'ベイズ最適化（Optuna）',
            'ウォークフォワード分析',
            'Pine Script v6 自動生成',
            '常に最新バージョン',
            '個人利用の範囲で複数端末対応',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
        {
          name: 'Monthly',
          badge: null,
          featured: false,
          price: '$19',
          period: '/ 月',
          desc: '月額サブスクリプション。必要な期間だけ最新バージョンを利用できます。',
          features: [
            'macOS / Linux / Windows 対応',
            'シミュレーション（回数無制限）',
            'ベイズ最適化（Optuna）',
            'ウォークフォワード分析',
            'Pine Script v6 自動生成',
            '常に最新バージョン',
            '個人利用の範囲で複数端末対応',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
      ],
      buyNow: '今すぐ購入',
      comingSummer: '今夏販売開始予定',
      note: 'ローンチ記念の早割 Lifetime $299 は先着50名・販売開始から2週間限定。早割枠が埋まるか期間が終了すると Lifetime は通常価格 $799 になります（合計100席上限）。Lifetime は v1.x 系の全アップデート対象、v2 リリース時は50%アップグレード料金で移行可能です。購入後にライセンスキーが発行され、forge license activate <KEY> で有効化します。',
      comparison: {
        label: 'プラン比較',
        colFree: 'Free',
        colPaid: '有料プラン（Lifetime / Annual / Monthly）',
        rows: [
          { feature: 'macOS / Linux / Windows 対応',    free: 'ok',    paid: 'ok' },
          { feature: 'バックテスト（シミュレーション）', free: 'limit', freeNote: '2023/12/31までのデータのみ', paid: 'ok', paidNote: '✓ 最新データ含む' },
          { feature: 'ウォークフォワード分析',           free: 'limit', freeNote: '2023/12/31までのデータのみ', paid: 'ok', paidNote: '✓ 最新データ含む' },
          { feature: 'ベイズ最適化（Optuna）',           free: 'limit', freeNote: '最大 50 回 / 実行',   paid: 'ok', paidNote: '✓ 回数無制限' },
          { feature: '最新ヒストリカルデータ取得',        free: 'no',    paid: 'ok' },
          { feature: 'Pine Script v6 自動生成',          free: 'no',    paid: 'ok' },
          { feature: 'メジャーバージョンアップデート',    free: 'ok',    paid: 'limit', paidNote: 'v1.x 系のみ。v2 は50%アップグレード料金' },
          { feature: '複数端末での利用',                  free: 'limit', freeNote: '1 端末のみ', paid: 'ok', paidNote: '✓ 個人利用の範囲で複数端末' },
        ],
      },
    },
    products: {
      label: 'プロダクト',
      title: '3つの層で構成される\n統合データ処理システム',
      subtitle: 'コーディングエージェントが投資戦略を半自動開発・最適化し、Pine Script を生成。外部シグナルをトリガーに strike が API リクエストを自動実行。',
      items: [
        {
          id: 'forge',
          badge: 'Beta',
          badgeType: 'beta',
          icon: '⚙',
          name: 'forge',
          role: 'シミュレーション・最適化エンジン',
          desc: '投資戦略定義をvectorbtで高速シミュレーション。Optunaによるベイズ最適化・ウォークフォワード検証で過学習を防ぎ、Pine Script v6を自動生成。Claude連携でパラメータを自律探索。',
          tags: ['Python', 'vectorbt', 'Optuna', 'Streamlit', 'Pine Script'],
          accent: 'var(--blue)',
        },
        {
          id: 'strategies',
          badge: 'Alpha',
          badgeType: 'alpha',
          icon: '◈',
          name: 'strategies',
          role: '投資戦略・データワークスペース',
          desc: '投資戦略定義・シミュレーション結果・最適化パラメータ・ジャーナルを一元管理。alpha-forgeの戦略レイヤーとして機能。実行ログの蓄積・分析も対応。',
          tags: ['TradingView', 'JSON', 'CLI', 'Pine Script', 'JSONL'],
          accent: 'var(--accent)',
        },
        {
          id: 'strike',
          badge: 'Dev',
          badgeType: 'dev',
          icon: '⚡',
          name: 'strike',
          role: 'Webhook・自動実行サーバー',
          desc: '外部 Webhook シグナルを FastAPI で受け取り、外部 API へ自動リクエスト送信。実行・レスポンスイベントをJSONLで記録。Dockerデプロイ対応。',
          tags: ['FastAPI', 'OANDA', 'moomoo', 'Docker', 'Webhook'],
          accent: 'var(--amber)',
        },
      ],
    },
    perf: {
      label: 'シミュレーション実績',
      title: 'シミュレーション結果（実データ）',
      strategy: 'CL=F 5年時系列データ — HMM + ボリンジャーバンド + RSI シミュレーション',
      period: '2021.05 – 2026.04（5年）',
      note: '※ 実際のシミュレーション結果です。コスト0.1%込み。QQQ B&H の年率（14.9%）は本シミュレーション（13.9%）を上回ります。過去の結果は将来の成果を保証しません。',
      stats: [
        { val: '+13.9%', label: 'CAGR',          cls: 'val-pos' },
        { val: '1.09',   label: 'Sharpe Ratio',   cls: 'val-neu' },
        { val: '86.4%',  label: 'シグナル正答率', cls: 'val-neu' },
        { val: '-17.0%', label: 'Max Drawdown',   cls: 'val-neg' },
        { val: '22回',   label: 'シグナル回数',   cls: 'val-neu' },
      ],
      legend: [
        { color: 'var(--accent)',  label: '本シミュレーション（CL=F）' },
        { color: 'var(--blue)',    label: 'SPY B&H' },
        { color: 'var(--amber)',   label: 'QQQ B&H' },
      ],
      bench: {
        label: 'vs ベンチマーク（同期間）',
        headers: ['', 'SPY B&H', 'QQQ B&H', '本シミュレーション'],
        rows: [
          { metric: 'CAGR',    spy: '12.6%', qqq: '14.9%', strat: '13.9%', stratWin: false },
          { metric: 'Sharpe',  spy: '≈0.5',  qqq: '≈0.5',  strat: '1.09',  stratWin: true },
          { metric: 'Max DD',  spy: '-23.9%',qqq: '-32.6%', strat: '-17.0%',stratWin: true },
        ],
      },
    },
    roadmap: {
      label: 'ロードマップ',
      title: '開発の軌跡と\nこれからの計画',
      items: [
        {
          period: '2026年3月上旬',
          status: 'done',
          badgeLabel: '完了',
          title: 'シミュレーションエンジン構築',
          items: ['シミュレーションエンジン設計・実装', 'データ取得・投資戦略スキーマ・CLI 構築', '最適化パイプライン・Pine Script 生成'],
        },
        {
          period: '2026年3月中旬〜下旬',
          status: 'done',
          badgeLabel: '完了',
          title: '分析機能拡充',
          items: ['HMM インジケータ・ウォークフォワード分析', 'バックテスト履歴 DB・チャート生成', 'リスク管理拡張（動的 SL/TP）'],
        },
        {
          period: '2026年3月末',
          status: 'done',
          badgeLabel: '完了',
          title: 'ライブ実行統合',
          items: ['alpha-strike Webhook サーバー構築', 'OANDA・moomoo API 自動実行対応', '実行・レスポンスイベント分析パイプライン'],
        },
        {
          period: '2026年4月',
          status: 'active',
          badgeLabel: '進行中',
          title: 'プロダクト化・製品化',
          items: ['Streamlit Web UI・マルチポートフォリオ最適化', 'ライセンス管理・バイナリ配布・CI/CD パイプライン', '公式サイト公開・Claude 連携自律探索'],
        },
        {
          period: '2026年5月',
          status: 'upcoming',
          badgeLabel: '予定',
          title: 'ベータ版公開',
          items: ['ベータ版バイナリリリース（macOS・Windows・Linux）', 'クローズドベータ開始・フィードバック収集', 'ドキュメント整備'],
        },
        {
          period: '2026年夏',
          status: 'upcoming',
          badgeLabel: '予定',
          title: '正式リリース・商用化',
          items: ['全プロダクト正式リリース', 'サポート・コミュニティ体制整備'],
        },
      ],
    },
    faq: {
      label: 'FAQ',
      title: 'よくある質問',
      items: [
        { q: 'どんな人向けですか？', a: 'Pythonの基礎知識があり、定量的なアプローチで投資戦略を開発したいソフトウェアエンジニア・クオンツ向けです。JSONで投資戦略を定義し、CLIで操作できます。将来的にはノーコードオプションも検討中です。' },
        { q: '現在、購入・利用できますか？', a: '現在はクローズドな開発フェーズです。リリース時期はXアカウント (@alforge_bot) でお知らせします。' },
        { q: '対応する外部APIは？', a: '現在はOANDA（FX・CFD API）とmoomoo（株式API）に対応しています。今後さらなる外部API拡充を予定しています。' },
        { q: 'TradingViewは必要ですか？', a: 'alpha-strikeの自動執行にはTradingViewのWebhookアラートを利用します。alpha-forgeのバックテスト・最適化はTradingView不要で動作します。' },
        { q: 'alpha-forgeはオープンソースですか？', a: '現在はクローズドでの開発を予定しています。公開方針については今後の開発状況を踏まえて改めてお知らせします。最新情報はX (@alforge_bot) をご確認ください。' },
      ],
    },
    systemFlow: {
      label: 'システム全体像',
      title: '探索から実行、実績データの蓄積までを一気通貫でつなぐ',
      subtitle: 'AlphaForgeで戦略を検証・最適化し、AlphaStrategiesに成果物を集約。TradingViewのアラートをAlphaStrikeが受け取り、Broker APIへ注文を送ります。約定・ポジション・損益データはLive Dataとして戻り、次の分析に活用します。',
      alt: 'AlphaTradeのシステムフロー図',
    },
    usecases: {
      label: '活用シーン',
      title: 'あらゆる市場・戦略スタイルに\n対応する定量フレームワーク',
      subtitle: 'AlphaForge の統計エンジンで、先物・株式・FX を問わず定量的な投資戦略の開発・検証・最適化サイクルをカバーします。',
      items: [
        {
          icon: '🛢️',
          accent: 'var(--amber)',
          label: 'Futures & Commodities',
          title: '先物・商品取引戦略',
          desc: 'WTI原油（CL=F）や金（GC=F）など商品先物市場に HMM 状態遷移モデルを適用。市場レジームの変化を自動検出し、ドローダウンを抑制しながら安定したリターンを追求します。',
          tags: ['先物取引', 'HMM', 'レジーム検出', 'CL=F / GC=F'],
        },
        {
          icon: '📈',
          accent: 'var(--blue)',
          label: 'Equity Index',
          title: '株式インデックス戦略',
          desc: 'S&P500（SPY）や NASDAQ100（QQQ）に MACD・RSI を組み合わせた複合戦略を構築。ウォークフォワード分析でロバストな長期パフォーマンスを厳密に検証します。',
          tags: ['株式インデックス', 'MACD / RSI', 'ウォークフォワード', 'SPY / QQQ'],
        },
        {
          icon: '💱',
          accent: 'var(--accent)',
          label: 'FX / Forex',
          title: '外国為替戦略',
          desc: 'USDJPY・EURUSD など主要通貨ペアへのベイズ最適化による高次元パラメータ探索。Grid Search より効率的に最適解を発見し、過剰最適化（曲線あてはめ）を防止します。',
          tags: ['FX 戦略', 'ベイズ最適化', '通貨ペア', 'USDJPY / EURUSD'],
        },
      ],
    },
    personaUseCases: {
      label: '誰向け？',
      title: 'あなたの目的から始める',
      subtitle: 'バックグラウンドや目的に合わせた入口を選んでください。',
      personas: [
        {
          icon: '📊',
          label: 'TradingView Users',
          title: 'TradingViewユーザー',
          desc: 'Pine Scriptでアイデアを試作し、AlphaForgeでバックテスト・最適化を本格化。Pine Script再エクスポートまで一気通貫。',
          link: '/ja/docs/usecases/tradingview/',
          linkLabel: '詳しく見る →',
        },
        {
          icon: '🐍',
          label: 'Python Developers',
          title: 'Python開発者',
          desc: 'JSON宣言型の戦略管理、CLIの構造化出力、Optunaベースの最適化。Pythonエコシステムとシームレスに連携。',
          link: '/ja/docs/usecases/python-dev/',
          linkLabel: '詳しく見る →',
        },
        {
          icon: '🔬',
          label: 'Quants & Researchers',
          title: 'クオンツ・研究者',
          desc: 'ウォークフォワード検証・ベイズ最適化・再現性保証。統計的な厳密性を求める研究者向けの定量評価環境。',
          link: '/ja/docs/usecases/quants/',
          linkLabel: '詳しく見る →',
        },
        {
          icon: '🤖',
          label: 'Automated Trading',
          title: '自動売買検討者',
          desc: 'バックテスト→最適化→Pine Script生成→TradingViewアラート→Alpha Strike自動発注まで一貫した環境。',
          link: '/ja/docs/usecases/auto-trading/',
          linkLabel: '詳しく見る →',
        },
        {
          icon: '✨',
          label: 'AI Agent Users',
          title: 'AIエージェント利用者',
          desc: 'Claude Codeなど AIエージェントと組み合わせて戦略探索を自動化。夜間に自律探索を回す非同期ワークフロー。',
          link: '/ja/docs/usecases/ai-agents/',
          linkLabel: '詳しく見る →',
        },
      ],
    },
    longTermValue: {
      label: '継続利用価値',
      title: '戦略は、作って終わりではない',
      subtitle: 'マーケット、研究、実装アイデアは変わり続けます。alpha-forge は一度きりの検証ツールではなく、戦略を見直し続けるための開発ループです。',
      items: [
        {
          eyebrow: 'Regime Shift',
          title: '市場レジームは変わる',
          desc: '一度よい結果を出した投資戦略でも、ボラティリティ・金利・流動性・参加者行動の変化で将来も機能し続けるとは限りません。定期的な再検証が必要です。',
        },
        {
          eyebrow: 'Strategy Intake',
          title: '新しいアイデアは増え続ける',
          desc: 'SSRN などの研究や TradingView の Pine Script コミュニティでは、新しい手法・指標・リスク管理アイデアが継続的に公開されています。検証候補を取り込める状態を保つことが重要です。',
        },
        {
          eyebrow: 'Validation Loop',
          title: '検証ループを回せる',
          desc: 'alpha-forge はバックテスト、ベイズ最適化、ウォークフォワード検証、Pine Script 生成を同じ流れで扱えます。発見した仮説を、再現可能な検証サイクルへ落とし込めます。',
        },
      ],
    },
    trustSafety: {
      label: '信頼・安全・制限',
      title: '購入・利用前に確認してほしいこと',
      subtitle: 'AlphaForge はローカル実行を前提にした開発者向けツールです。データの扱い、ライセンス認証、投資リスク、プラン制限をまとめて確認できます。',
      docsHref: '/ja/docs/legal/trust-safety-limits/',
      docsLabel: '信頼・安全・制限の詳細を読む',
      items: [
        {
          eyebrow: 'Local First',
          title: '戦略データはローカルに残る',
          desc: 'バックテスト設定、API キー・取引履歴・戦略データは通常ローカル環境に留まり、Alforge Labs のサーバーへ送信されません。',
        },
        {
          eyebrow: 'License',
          title: '認証時のみ必要情報を送信',
          desc: 'ライセンス認証時には、ライセンスキー、インスタンス名、アクティベーション日時など、認証に必要な情報だけが外部サービスへ送信されます。',
        },
        {
          eyebrow: 'Risk',
          title: '投資助言ではありません',
          desc: 'AlphaForge は研究・検証用ソフトウェアです。バックテストやシミュレーション結果は将来の成果を保証せず、取引判断はユーザー自身の責任です。',
        },
        {
          eyebrow: 'Plans',
          title: 'Free / Monthly / Annual / Lifetime',
          desc: 'Free プランにはデータ日付と最適化 trial 数の制限があります。有料プランでは最新データと無制限 trial を利用できます。',
        },
      ],
    },
    follow: {
      label: 'アップデート',
      title: '開発をリアルタイムで追う',
      desc: 'シミュレーション実績レポート・機能アップデート・開発の裏側を定期発信しています。',
      cta: 'X でフォローする',
    },
    disclaimer: {
      title: '⚠️ 重要な免責事項（必ずお読みください）',
      items: [
        { label: 'ソフトウェアの提供', text: '本製品は、時系列データのシミュレーションおよびデータパイプライン自動化を支援する「開発者向けソフトウェアツール」の提供です。特定の運用方法を推奨するものではありません。' },
        { label: 'シミュレーション結果について', text: '本ソフトウェアのシミュレーション結果は過去データに基づくものであり、将来の成果を保証するものではありません。' },
        { label: '利用責任', text: 'パラメータの設定およびシステムトラブルによる影響を含め、本ソフトウェアの利用はすべてユーザー自身の責任の下で行ってください。' },
      ],
    },
    footer: {
      copy: '© 2026 Alforge Labs.',
      note: 'このサイトは開発者向けソフトウェアツールを提供します。特定の投資・運用を推奨するものではありません。',
      links: [
        { label: 'インストール', url: '/install.html' },
        { label: 'ドキュメント', url: '/ja/docs/' },
        { label: '利用規約', url: '/terms.html' },
        { label: 'プライバシー', url: '/privacy.html' },
      ],
    },
  },

  en: {
    nav: { products: 'Products', pricing: 'Pricing', install: 'Install', docs: 'Docs', roadmap: 'Roadmap', faq: 'FAQ', follow: 'Follow' },
    hero: {
      tag: 'In Development',
      h1a: 'From Noise',
      h1b: 'to Signal.',
      desc: 'Backtest, Bayesian optimization, and walk-forward validation — unified in a single CLI. Systematically develop and validate investment strategies with reproducible statistical edge across futures, equities, and FX.',
      cta1: 'Start Free',
      cta2: 'See Plans',
    },
    freeStart: {
      label: 'Start Free',
      title: 'Start validating for free',
      subtitle: 'The Free plan lets you try backtesting, walk-forward analysis, and Bayesian optimization locally. Start with a sample strategy and see the AlphaForge validation flow before choosing a paid plan.',
      primaryCta: 'Go to install',
      secondaryCta: 'Compare plans',
      updateCta: 'Follow updates on X',
      availability: 'Free registration and paid plans are scheduled for this summer. For now, you can review the install flow and plan limits.',
      outExamplesCta: 'See output samples',
      steps: [
        { num: '01', title: 'Install', desc: 'Set up the CLI on macOS, Linux, or Windows.' },
        { num: '02', title: 'Run a sample strategy', desc: 'Try the validation flow with a ready-made strategy JSON.' },
        { num: '03', title: 'Review results', desc: 'Inspect metrics, the equity curve, and optimization results within Free limits.' },
      ],
      limits: [
        'Data through Dec 31, 2023',
        '50 optimization trials',
        'No Pine Script export',
      ],
    },
    heroStats: [
      { val: '3', accent: false, lbl: 'Products in Dev' },
      { val: 'Sharpe 1.09', accent: true, lbl: 'Simulation Result (CL=F · 5yr data)' },
      { val: 'Summer 2026', accent: false, lbl: 'Target Release' },
    ],
    pricing: {
      label: 'Pricing',
      title: 'Choose the plan\nthat fits your workflow.',
      subtitle: 'Launch promo: First 50 buyers get Lifetime at $299 (vs the regular $799). Annual and Monthly stay at standard pricing.',
      freePlan: {
        title: 'Start with Free',
        badge: 'Free',
        desc: 'Try backtesting, Bayesian optimization, and walk-forward analysis at no cost.\nHistorical data up to Dec 31, 2023 · 50 optimization trials per run · No Pine Script export.',
        pills: [
          { label: '✓ Backtest',           type: 'ok' },
          { label: '✓ Walk-Forward',       type: 'ok' },
          { label: 'Optimization 50 trials max', type: 'limit' },
          { label: 'Data up to Dec 31, 2023', type: 'limit' },
          { label: 'Pine Script export',   type: 'no' },
        ],
        ctaLabel: 'Register for $0',
        ctaHint: 'View install steps',
        comingSummer: 'Coming This Summer',
      },
      plans: [
        {
          name: 'Lifetime (Early Bird)',
          badge: 'Launch Promo · First 50',
          featured: true,
          price: '$299',
          period: 'one-time',
          desc: 'Launch promo for the first 2 weeks · first 50 buyers only. Regular Lifetime is $799. Covers all v1.x major version updates.',
          features: [
            'macOS / Linux / Windows',
            'Unlimited simulations',
            'Bayesian optimization (Optuna)',
            'Walk-forward analysis',
            'Pine Script v6 auto-generation',
            'All v1.x updates included (v2 = 50% upgrade fee)',
            'Personal use across multiple devices',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
        {
          name: 'Annual',
          badge: null,
          featured: false,
          price: '$159',
          period: '/ year',
          desc: 'Annual subscription. ~30% off vs monthly. Always on the latest version.',
          features: [
            'macOS / Linux / Windows',
            'Unlimited simulations',
            'Bayesian optimization (Optuna)',
            'Walk-forward analysis',
            'Pine Script v6 auto-generation',
            'Always on the latest version',
            'Personal use across multiple devices',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
        {
          name: 'Monthly',
          badge: null,
          featured: false,
          price: '$19',
          period: '/ month',
          desc: 'Monthly subscription. Use the latest version for as long as you need it.',
          features: [
            'macOS / Linux / Windows',
            'Unlimited simulations',
            'Bayesian optimization (Optuna)',
            'Walk-forward analysis',
            'Pine Script v6 auto-generation',
            'Always on the latest version',
            'Personal use across multiple devices',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
      ],
      buyNow: 'Get Access',
      comingSummer: 'Coming This Summer',
      note: 'Early Bird Lifetime ($299) is limited to the first 50 buyers within the 2 weeks after launch. Once seats are sold or the window closes, Lifetime returns to $799 (capped at 100 total seats). Lifetime covers all v1.x updates; v2 will be available at a 50% upgrade fee. A license key is issued after purchase. Activate with: forge license activate <KEY>',
      comparison: {
        label: 'Plan Comparison',
        colFree: 'Free',
        colPaid: 'Paid Plans (Lifetime / Annual / Monthly)',
        rows: [
          { feature: 'macOS / Linux / Windows',          free: 'ok',    paid: 'ok' },
          { feature: 'Backtest (simulation)',             free: 'limit', freeNote: 'Historical data up to Dec 31, 2023', paid: 'ok', paidNote: '✓ Latest data included' },
          { feature: 'Walk-forward analysis',            free: 'limit', freeNote: 'Historical data up to Dec 31, 2023', paid: 'ok', paidNote: '✓ Latest data included' },
          { feature: 'Bayesian optimization (Optuna)',   free: 'limit', freeNote: 'Up to 50 trials per run',   paid: 'ok', paidNote: '✓ Unlimited' },
          { feature: 'Latest historical data download',  free: 'no',    paid: 'ok' },
          { feature: 'Pine Script v6 auto-generation',   free: 'no',    paid: 'ok' },
          { feature: 'Major version updates',             free: 'ok',    paid: 'limit', paidNote: 'v1.x only. v2 = 50% upgrade fee' },
          { feature: 'Multi-device use',                  free: 'limit', freeNote: '1 device only', paid: 'ok', paidNote: '✓ Personal use across devices' },
        ],
      },
    },
    products: {
      label: 'Products',
      title: 'Three layers.\nOne integrated system.',
      subtitle: 'AI-driven investment strategy development and optimization with Pine Script generation. External signals trigger strike for automated API execution.',
      items: [
        {
          id: 'forge',
          badge: 'Beta',
          badgeType: 'beta',
          icon: '⚙',
          name: 'forge',
          role: 'Simulation & Optimization Engine',
          desc: 'Simulate investment strategies at high speed with vectorbt. Bayesian optimization via Optuna + walk-forward validation to prevent overfitting. Automatic Pine Script v6 generation. Claude integration for autonomous parameter exploration.',
          tags: ['Python', 'vectorbt', 'Optuna', 'Streamlit', 'Pine Script'],
          accent: 'var(--blue)',
        },
        {
          id: 'strategies',
          badge: 'Alpha',
          badgeType: 'alpha',
          icon: '◈',
          name: 'strategies',
          role: 'Strategy & Data Workspace',
          desc: 'Unified management of investment strategy definitions, simulation results, optimized parameters, and journals. Acts as the strategy layer for alpha-forge. Supports execution log accumulation and analysis.',
          tags: ['TradingView', 'JSON', 'CLI', 'Pine Script', 'JSONL'],
          accent: 'var(--accent)',
        },
        {
          id: 'strike',
          badge: 'Dev',
          badgeType: 'dev',
          icon: '⚡',
          name: 'strike',
          role: 'Webhook Execution Server',
          desc: 'Receives external webhook signals via FastAPI and auto-routes API requests to OANDA and moomoo. Records execution and response events as JSONL. Docker-ready for server deployment.',
          tags: ['FastAPI', 'OANDA', 'moomoo', 'Docker', 'Webhook'],
          accent: 'var(--amber)',
        },
      ],
    },
    perf: {
      label: 'Simulation Results',
      title: 'Simulation Results (Live Data)',
      strategy: 'CL=F 5yr Time-Series Data — HMM + Bollinger Bands + RSI Simulation',
      period: '2021.05 – 2026.04 (5 years)',
      note: '* Real simulation result with 0.1% cost. QQQ buy-and-hold CAGR (14.9%) exceeds this simulation (13.9%). Past results do not guarantee future outcomes.',
      stats: [
        { val: '+13.9%', label: 'CAGR',            cls: 'val-pos' },
        { val: '1.09',   label: 'Sharpe Ratio',     cls: 'val-neu' },
        { val: '86.4%',  label: 'Signal Accuracy',  cls: 'val-neu' },
        { val: '-17.0%', label: 'Max Drawdown',      cls: 'val-neg' },
        { val: '22',     label: 'Total Signals',     cls: 'val-neu' },
      ],
      legend: [
        { color: 'var(--accent)', label: 'This Simulation (CL=F)' },
        { color: 'var(--blue)',   label: 'SPY B&H' },
        { color: 'var(--amber)',  label: 'QQQ B&H' },
      ],
      bench: {
        label: 'vs Benchmark (same period)',
        headers: ['', 'SPY B&H', 'QQQ B&H', 'This Simulation'],
        rows: [
          { metric: 'CAGR',    spy: '12.6%', qqq: '14.9%', strat: '13.9%', stratWin: false },
          { metric: 'Sharpe',  spy: '≈0.5',  qqq: '≈0.5',  strat: '1.09',  stratWin: true },
          { metric: 'Max DD',  spy: '-23.9%',qqq: '-32.6%', strat: '-17.0%',stratWin: true },
        ],
      },
    },
    roadmap: {
      label: 'Roadmap',
      title: 'Where we\'ve been\nand where we\'re going.',
      items: [
        { period: 'Early March 2026', status: 'done', badgeLabel: 'Done', title: 'Simulation Engine Build', items: ['Simulation engine design & build', 'Data ingestion, investment strategy schema & CLI', 'Optimization pipeline & Pine Script generation'] },
        { period: 'Mid–Late March 2026', status: 'done', badgeLabel: 'Done', title: 'Analysis Feature Expansion', items: ['HMM indicator + walk-forward analysis', 'Backtest history DB & chart generation', 'Risk management (dynamic SL/TP)'] },
        { period: 'Late March 2026', status: 'done', badgeLabel: 'Done', title: 'Live Execution Integration', items: ['alpha-strike Webhook server', 'OANDA & moomoo API execution', 'Execution & response event analysis pipeline'] },
        { period: 'April 2026', status: 'active', badgeLabel: 'Active', title: 'Productization', items: ['Streamlit Web UI & multi-portfolio optimization', 'License management, binary distribution & CI/CD pipeline', 'Official site launch & Claude-driven parameter search'] },
        { period: 'May 2026', status: 'upcoming', badgeLabel: 'Planned', title: 'Beta Release', items: ['Binary release for macOS, Windows & Linux', 'Closed beta & feedback collection', 'Documentation polish'] },
        { period: 'Summer 2026', status: 'upcoming', badgeLabel: 'Planned', title: 'Public Launch', items: ['Full product release', 'Support & community setup'] },
      ],
    },
    faq: {
      label: 'FAQ',
      title: 'Frequently Asked\nQuestions',
      items: [
        { q: 'Who is this for?', a: 'Software engineers and quantitative researchers with basic Python knowledge who want a systematic approach to building investment strategies. Investment strategies are defined in JSON and operated via CLI. No-code options are on the roadmap.' },
        { q: 'Can I use it now?', a: 'We\'re in closed development. Follow @alforge_bot on X for release announcements.' },
        { q: 'Which external APIs are supported?', a: 'Currently OANDA (FX/CFD API) and moomoo (equities API). More API integrations are planned.' },
        { q: 'Do I need TradingView?', a: 'alpha-strike can receive TradingView Webhook alerts. alpha-forge simulations and optimization work independently of TradingView.' },
        { q: 'Is alpha-forge open source?', a: 'We plan to keep alpha-forge closed source. Details on our licensing and release model will be shared as development progresses. Follow @alforge_bot for updates.' },
      ],
    },
    systemFlow: {
      label: 'System Flow',
      title: 'Connect research, execution, and live feedback in one loop',
      subtitle: 'AlphaForge builds and optimizes strategies, AlphaStrategies stores deliverables, and AlphaStrike receives TradingView alerts to send orders through Broker APIs. Fills, positions, and P&L return as Live Data for the next analysis cycle.',
      alt: 'AlphaTrade system flow diagram',
    },
    usecases: {
      label: 'Use Cases',
      title: 'A Quant Framework for\nEvery Market and Strategy Style',
      subtitle: 'AlphaForge\'s statistical engine covers the full development, validation, and optimization cycle for quantitative investment strategies — across futures, equities, and FX.',
      items: [
        {
          icon: '🛢️',
          accent: 'var(--amber)',
          label: 'Futures & Commodities',
          title: 'Futures & Commodity Trading',
          desc: 'Apply HMM regime-switching models to commodity futures like crude oil (CL=F) and gold (GC=F). Automatically detect market regime changes and pursue stable returns while limiting drawdown.',
          tags: ['Futures Trading', 'HMM', 'Regime Detection', 'CL=F / GC=F'],
        },
        {
          icon: '📈',
          accent: 'var(--blue)',
          label: 'Equity Index',
          title: 'Equity Index Strategies',
          desc: 'Build multi-indicator strategies combining MACD and RSI on S&P 500 (SPY) and NASDAQ 100 (QQQ). Rigorously validate long-term performance with walk-forward analysis.',
          tags: ['Equity Index', 'MACD / RSI', 'Walk-Forward', 'SPY / QQQ'],
        },
        {
          icon: '💱',
          accent: 'var(--accent)',
          label: 'FX / Forex',
          title: 'Forex Strategies',
          desc: 'Run Bayesian optimization across high-dimensional parameter spaces for major pairs like USDJPY and EURUSD. Find optimal solutions more efficiently than grid search while preventing curve-fitting.',
          tags: ['FX Strategy', 'Bayesian Optimization', 'Currency Pairs', 'USDJPY / EURUSD'],
        },
      ],
    },
    personaUseCases: {
      label: 'Who Is It For?',
      title: 'Start From Your Goal',
      subtitle: 'Choose the entry point that matches your background and goals.',
      personas: [
        {
          icon: '📊',
          label: 'TradingView Users',
          title: 'TradingView Users',
          desc: 'Prototype in Pine Script and bring the real backtesting and optimization to AlphaForge. Export Pine Script back when done.',
          link: '/en/docs/usecases/tradingview/',
          linkLabel: 'Learn more →',
        },
        {
          icon: '🐍',
          label: 'Python Developers',
          title: 'Python Developers',
          desc: 'JSON-declarative strategy management, structured CLI output, and Optuna-based optimization — seamlessly integrated with the Python ecosystem.',
          link: '/en/docs/usecases/python-dev/',
          linkLabel: 'Learn more →',
        },
        {
          icon: '🔬',
          label: 'Quants & Researchers',
          title: 'Quants & Researchers',
          desc: 'Walk-forward validation, Bayesian optimization, and reproducibility guarantees. A quantitative evaluation environment for researchers who demand statistical rigor.',
          link: '/en/docs/usecases/quants/',
          linkLabel: 'Learn more →',
        },
        {
          icon: '🤖',
          label: 'Automated Trading',
          title: 'Automated Trading',
          desc: 'A complete pipeline: backtest → optimize → generate Pine Script → TradingView alert → Alpha Strike auto-execution.',
          link: '/en/docs/usecases/auto-trading/',
          linkLabel: 'Learn more →',
        },
        {
          icon: '✨',
          label: 'AI Agent Users',
          title: 'AI Agent Users',
          desc: 'Combine with Claude Code or other AI agents to automate strategy exploration. Run autonomous overnight discovery loops without human intervention.',
          link: '/en/docs/usecases/ai-agents/',
          linkLabel: 'Learn more →',
        },
      ],
    },
    longTermValue: {
      label: 'Long-Term Value',
      title: 'Strategies are never finished',
      subtitle: 'Markets, research, and implementation ideas keep changing. alpha-forge is not a one-off backtest tool; it is a development loop for continuously revisiting your strategy assumptions.',
      items: [
        {
          eyebrow: 'Regime Shift',
          title: 'Market regimes change',
          desc: 'A strategy that looks strong once may degrade as volatility, rates, liquidity, and participant behavior shift. Long-lived systems need periodic revalidation instead of one-time confidence.',
        },
        {
          eyebrow: 'Strategy Intake',
          title: 'New ideas keep arriving',
          desc: 'Research platforms such as SSRN and the TradingView Pine Script community continue to surface new methods, indicators, and risk-management ideas. Keeping an intake path open helps turn them into testable candidates.',
        },
        {
          eyebrow: 'Validation Loop',
          title: 'Keep the validation loop moving',
          desc: 'alpha-forge keeps backtesting, Bayesian optimization, walk-forward validation, and Pine Script generation in one flow. New hypotheses can move into reproducible validation without rebuilding the workflow each time.',
        },
      ],
    },
    trustSafety: {
      label: 'Trust, Safety, and Limits',
      title: 'What to know before you buy or use AlphaForge',
      subtitle: 'AlphaForge is a developer tool built around local execution. Review how data is handled, what license activation sends, what the investment-risk limits are, and how plan limits work.',
      docsHref: '/en/docs/legal/trust-safety-limits/',
      docsLabel: 'Read the Trust, Safety, and Limits guide',
      items: [
        {
          eyebrow: 'Local First',
          title: 'Strategy data stays local',
          desc: 'Backtest settings, API keys, trade history, and strategy data normally remain in your local environment and are not sent to Alforge Labs servers.',
        },
        {
          eyebrow: 'License',
          title: 'Activation sends only required license data',
          desc: 'During license activation, only information required for verification, such as the license key, instance name, and activation timestamp, is sent to the external license service.',
        },
        {
          eyebrow: 'Risk',
          title: 'This is not financial advice',
          desc: 'AlphaForge is research and validation software. Backtests and simulation results do not guarantee future outcomes, and every trading decision remains your responsibility.',
        },
        {
          eyebrow: 'Plans',
          title: 'Free / Monthly / Annual / Lifetime',
          desc: 'The Free plan has data-date and optimization trial limits. Paid plans can use the latest data and unlimited trials.',
        },
      ],
    },
    follow: {
      label: 'Updates',
      title: 'Follow the build\nin real time.',
      desc: 'Simulation results, feature updates, and behind-the-scenes development shared regularly.',
      cta: 'Follow on X',
    },
    disclaimer: {
      title: '⚠️ Important Disclaimer (Please Read)',
      items: [
        { label: 'Software Provision', text: 'This product is a developer software tool for time-series data simulation and pipeline automation. It does not recommend any specific operational approach.' },
        { label: 'About Simulation Results', text: 'Simulation results are based on historical data and do not guarantee future outcomes.' },
        { label: 'User Responsibility', text: 'All outcomes, including those from automated API execution, parameter settings, and system errors, are the sole responsibility of the user.' },
      ],
    },
    footer: {
      copy: '© 2026 Alforge Labs.',
      note: 'This site provides developer software tools. Nothing here constitutes professional advice or specific product recommendations.',
      links: [
        { label: 'Install', url: '/install.html' },
        { label: 'Docs', url: '/en/docs/' },
        { label: 'Terms', url: '/terms.html' },
        { label: 'Privacy', url: '/privacy.html' },
      ],
    },
  },
};
